name: ci-test

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: "Update test env"
    runs-on: ubuntu-latest
    environment:
      name: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js runtime
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup prereqs
        run: |
          npm install -g lerna
          npm install -g typescript
          npm install -g yarn
          yarn install
          lerna bootstrap

      - name: Build dapp
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          FAST_REFRESH: true
          BROWSER: false
          HTTPS: true
          REACT_APP_LOG_LEVEL: debug
          REACT_APP_MODE: production
          REACT_APP_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          REACT_APP_FILE_WEB3STORAGE_KEY: ${{ secrets.FILE_WEB3STORAGE_KEY }}
          REACT_APP_NETWORK_ID: ${{ secrets.NETWORK_ID }}
          REACT_APP_NETWORK_PROVIDER: ${{ secrets.NETWORK_PROVIDER }}
          REACT_APP_CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          REACT_APP_SEARCH_FORM_DISABLED: ${{ secrets.SEARCH_FORM_DISABLED }}
        run: |
          rm -rf ./docs
          mkdir -p ./docs
          cd ./packages/dapp/
          rm -rf ./build
          yarn ghpages

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './docs'
          production-branch: main
          production-deploy: true
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
